version: "3.9"
services:

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  loanrangers:
    container_name: loanrangers
    image: theloanrangers
    restart: unless-stopped
    ports:
      - "3838:3838"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --agree-tos --email <EMAIL_ADDRESS> -d loanrangers.info -d www.loanrangers.info
