version: "3.9"
services:

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf

  loanrangers:
    container_name: loanrangers
    image: theloanrangers
    restart: unless-stopped
    ports:
        - "3838:3838"
        